### ISSUE TITLE
SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by palangmerah** [posm/posm.github.io#1]
I'm getting the following error, when trying **yarn run develop**:

> root@pmi:~/posm.github.io# yarn run develop
> yarn run v0.24.5
> $ gatsby develop
> bin/gatsby: time since started: 0.058
> bin/cli: time since started: 0.185
> time to load develop: 1250ms
> initial loading: 1383ms
> lib/bootstrap/index.js time since started: 1.446
> open and validate gatsby-config.js: 6ms
> copy gatsby files: 20ms
> calling api handler in /root/posm.github.io/node_modules/gatsby-source-filesystem for api sourceNodes
> calling api handler in /root/posm.github.io/node_modules/gatsby-source-filesystem for api sourceNodes
> /root/posm.github.io/gatsby-node.js:9
> exports.createPages = ({ graphql, boundActionCreators }) => {
>                        ^
> 
> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at runAPI (/root/posm.github.io/node_modules/gatsby/dist/utils/api-runner-node.js:89:20)
>     at /root/posm.github.io/node_modules/gatsby/dist/utils/api-runner-node.js:136:33
>     at /root/posm.github.io/node_modules/async/internal/map.js:27:9
>     at replenish (/root/posm.github.io/node_modules/async/internal/eachOfLimit.js:64:17)
>     at iterateeCallback (/root/posm.github.io/node_modules/async/internal/eachOfLimit.js:49:17)
>     at /root/posm.github.io/node_modules/async/internal/onlyOnce.js:12:16
>     at /root/posm.github.io/node_modules/async/internal/map.js:29:13
>     at tryCatcher (/root/posm.github.io/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise.successAdapter (/root/posm.github.io/node_modules/bluebird/js/release/nodeify.js:23:30)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sethfitz** [comment]
Hi @palangmerah. This project requires Node-6.x; I'm guessing that the syntax error is coming from an older version.
